config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout"},
    controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root to: 'users#show'

  resources :users, only: [:index, :show] do
    member do
      get 'get_cards'
      post 'post_cards'
    end
  end

  get 'results' => 'events#result'

  get 'poll_event/:id' => 'events#polled'
  get 'poll_result/:id/with/:card_id' => 'events#polled_result'
  post 'push_event/:id/with/:card_id' => 'events#pushed'

  # TwitterStreamingAPI
  namespace 'api', :module => 'api' do
    get    'tweet'       => 'tweet#index'
    get    'trend'       => 'trend#index'
  end
end

app/views/templates/_event_info.html.slim
ul.events style="padding:0"
  - @recent_events.each do |event|
    li class="event-#{event.id}"
      .well.well-sm
      	h5 
      	  | トレンドは
      	  b = event.trend_word
      	  | です。
      	h6.time = (event.created_at + 3.minutes).strftime('%y/%m/%d %H:%M:%S')
      	p 参加人数は#{event.try(:cards).try(:count) || 0}人です

app/views/templates/_footer.html.slim
.jumbotron
  h6.text-center アカウントを奪い合う『Twitter Wars』　Copyright© 2016 Huraibo All Rights Reserved.

app/views/templates/_header.html.erb
nav#js-bootstrap-offcanvas.navbar.navbar-default.navbar-fixed-top role="navigation"
  .container-fluid style="padding: 0 10%"
    .navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target="#navbar"
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = image_tag "logo.png"

    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to '#', id: "intro_btn", class: "hidden-xs" do
            = image_tag "info.png"
        li
          = link_to new_evideo_path, class: 'new_evideo' do
            i.glyphicon.glyphicon-plus
            |  動画投稿

        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
              = thumbnail current_user.thumb(:thumb)
              span.username
                = current_user.username

            ul.dropdown-menu
              li
                h5.text-center style="color: #333;margin:0"
                  span style="font-size: 20px; font-weight: bold;"
                    = current_user.status.level
                  b Lv.
                .progress
                  .progress-bar role="progressbar" aria-valuenow="#{@user_score}" aria-valuemin="0" aria-valuemax="100" style="width: #{@user_score}%"
                    span #{@user_score}%
              li
                = link_to user_path(current_user.id) do
                  i.glyphicon.glyphicon-user
                  |  マイページ 
              li
                = link_to edit_user_registration_path do
                  i.glyphicon.glyphicon-cog
                  |  プロフィール変更
              li
                = link_to destroy_user_session_path, method: :delete do
                  i.glyphicon.glyphicon-off
                  |  ログアウト
        - else
          li
            a href="/users/login"
              i.glyphicon.glyphicon-user
              |  サインアップ   
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
              i.glyphicon.glyphicon-log-in
              |  ログイン 
            ul.dropdown-menu.login
              li
                = link_to user_omniauth_authorize_path(:twitter), class: 'TwBtn' do
                  i.fa.fa-twitter.fa-2x
                  | でログイン 
              li
                = link_to user_omniauth_authorize_path(:facebook), class: 'FbBtn' do
                  i.fa.fa-facebook.fa-2x
                  | でログイン 

app/views/templates/_header.html.slim
nav#js-bootstrap-offcanvas.navbar.navbar-default.navbar-fixed-top role="navigation"
  .container-fluid style="padding: 0 10%"
    .navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target="#navbar"
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = image_tag "logo.png"

    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          /= link_to new_evideo_path, class: 'new_evideo' do
          /  i.glyphicon.glyphicon-plus
          /  |  動画投稿

        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
              = thumbnail current_user.thumbnail
              span.username
                = current_user.username

            ul.dropdown-menu
              li
                h5.text-center style="color: #333;margin:0"
                  span style="font-size: 20px; font-weight: bold;"
                    = current_user.score / 60
                  b Lv.
                .progress
                  .progress-bar role="progressbar" aria-valuenow="#{@user_score}" aria-valuemin="0" aria-valuemax="100" style="width: #{@user_score}%"
                    span #{@user_score}%
              li
                = link_to user_path(current_user.id) do
                  i.glyphicon.glyphicon-user
                  |  マイページ 
              li
                = link_to users_path do
                  i.glyphicon.glyphicon-list-alt
                  |  ユーザ一覧
              li
                = link_to destroy_user_session_path, method: :delete do
                  i.glyphicon.glyphicon-off
                  |  ログアウト
        - else
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
              i.glyphicon.glyphicon-log-in
              |  ログイン 
            ul.dropdown-menu.login
              li
                = link_to user_omniauth_authorize_path(:twitter), class: 'TwBtn' do
                  i.fa.fa-twitter.fa-2x
                  | Twitterでログイン 

app/views/templates/_tl.html.slim
ul.tweets style="padding:0"

app/views/templates/_trend.html.erb
<iframe scrolling="no" style="border:none;" width="540" height="240" src="https://www.google.com/trends/fetchComponent?hl=ja-JP&q=danbo+robot,danbo+amazon,danbo+yotsuba &cmpt=q&content=1&cid=TIMESERIES_GRAPH_0&export=5&w=500&h=160"></iframe>

app/views/templates/_user_info.html.slim
section
  .container-fluid
    .row
      .col-sm-4.text-center
        .thumbnail style="width:90%;margin:0 auto;margin-top:40px;"
          = thumbnail @user.thumbnail, class: 'thumb', style: 'width: 100%;'   
        h3 #{@user.username}   
      .col-sm-8 style="margin-top: 0px;"
        .col-sm-4
          section.user_level
            span #{@user.score / 60}
            b Lv.
        .cols-m-7
          section.user_progress
            .progress style="margin-top:35px;"
              .progress-bar role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width:0%"
                span 0%
            .user_score
              = @user.score
              | score
        section.user_myself style="margin-top:20px;"
          table.table.table-striped.table-hover
            tbody
              tr
                td 勝率
                td #{@user.win}勝#{@user.lose}敗 | #{winning_percentage @user.win, @user.lose}
              tr
                td 総アカウント数
                td = @user.cards.count
              tr
                td 総フォロワー数
                td #{@user.cards.sum(:followers_count)}人
              tr 
                td 総ツイート数
                td #{@user.cards.sum(:tweets_count)}人